/* Push-Up Tracker: local-first state, editable history, and presentation logic. */
const STORAGE_KEY = 'push-up-tracker.v1';
const TRACKING_START_DATE = '2026-07-26';
const defaultState = () => ({ version: 4, activeDate: dateKey(new Date()), count: 0, goal: 50, history: {} });
let state = loadState();
let selectedHistoryDate = dateKey(new Date());
let historyMonth = new Date(new Date().getFullYear(), new Date().getMonth(), 1);
let resetStep = 0;

const el = (id) => document.getElementById(id);
function dateKey(date) { const y = date.getFullYear(); const m = String(date.getMonth() + 1).padStart(2, '0'); const d = String(date.getDate()).padStart(2, '0'); return `${y}-${m}-${d}`; }
function parseDate(key) { const [y, m, d] = key.split('-').map(Number); return new Date(y, m - 1, d); }
function addDays(date, days) { const copy = new Date(date); copy.setDate(copy.getDate() + days); return copy; }
function datesEqual(a, b) { return dateKey(a) === dateKey(b); }
function isBeforeToday(date) { const day = new Date(date.getFullYear(), date.getMonth(), date.getDate()); const today = new Date(); today.setHours(0, 0, 0, 0); return day < today; }
function isTrackedKey(key) { return key >= TRACKING_START_DATE; }
function normaliseHistory(history) { return Object.fromEntries(Object.entries(history || {}).filter(([key]) => isTrackedKey(key)).map(([key, record]) => { if (typeof record === 'boolean') return [key, { count: record ? null : 0, goal: null, completed: record }]; return [key, { count: Number.isInteger(record.count) ? record.count : 0, goal: record.goal || null, completed: Boolean(record.completed) }]; })); }
function loadState() { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)); return { ...defaultState(), ...saved, version: 4, history: normaliseHistory(saved.history) }; } catch { return defaultState(); } }
function saveState() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function archiveRecord(count, goal) { return { count, goal, completed: count >= goal }; }
function recordFor(key) { return key === state.activeDate ? archiveRecord(state.count, state.goal) : state.history[key]; }

function reconcileDate() { const today = dateKey(new Date()); if (state.activeDate === today) return; let cursor = parseDate(state.activeDate); const todayDate = parseDate(today); while (cursor < todayDate) { const key = dateKey(cursor); if (isTrackedKey(key) && !(key in state.history)) state.history[key] = key === state.activeDate ? archiveRecord(state.count, state.goal) : archiveRecord(0, state.goal); cursor = addDays(cursor, 1); } state.activeDate = today; state.count = 0; saveState(); }
function calculateStreak() { let cursor = new Date(); let streak = 0; if (state.count >= state.goal) { streak = 1; cursor = addDays(cursor, -1); } else cursor = addDays(cursor, -1); while (isTrackedKey(dateKey(cursor)) && recordFor(dateKey(cursor))?.completed) { streak++; cursor = addDays(cursor, -1); } return streak; }
function changeCount(amount) { reconcileDate(); state.count = Math.max(0, state.count + amount); saveState(); render(); }
function statusFor(key, day) { if (!isTrackedKey(key) || (!isBeforeToday(day) && key !== state.activeDate)) return '⬜'; return recordFor(key)?.completed ? '✅' : key === state.activeDate ? '⬜' : '❌'; }
function renderWeek() { const today = new Date(); const sunday = addDays(today, -today.getDay()); const names = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']; el('week-grid').innerHTML = names.map((name, index) => { const day = addDays(sunday, index); const key = dateKey(day); const status = statusFor(key, day); return `<div class="day ${datesEqual(day, today) ? 'today' : ''}"><span>${name}</span><span class="day-mark" aria-label="${name}: ${status}">${status}</span></div>`; }).join(''); }
function renderHistory() {
  const monthLabel = new Intl.DateTimeFormat(undefined, { month: 'long', year: 'numeric' }).format(historyMonth); el('calendar-month').textContent = monthLabel;
  const firstDay = new Date(historyMonth.getFullYear(), historyMonth.getMonth(), 1); const daysInMonth = new Date(historyMonth.getFullYear(), historyMonth.getMonth() + 1, 0).getDate(); const cells = Array.from({ length: firstDay.getDay() }, () => '<span class="calendar-day empty"></span>');
  for (let dayNumber = 1; dayNumber <= daysInMonth; dayNumber++) { const day = new Date(historyMonth.getFullYear(), historyMonth.getMonth(), dayNumber); const key = dateKey(day); const record = recordFor(key); const untracked = !isTrackedKey(key); const future = !isBeforeToday(day) && key !== state.activeDate; const stateClass = untracked ? 'untracked' : record?.completed ? 'complete' : record ? 'incomplete' : future ? 'future' : 'untracked'; const disabled = future || untracked; cells.push(`<button class="calendar-day ${stateClass} ${key === selectedHistoryDate ? 'selected' : ''}" data-history-date="${key}" type="button"${disabled ? ' disabled' : ''} aria-label="${dayNumber}, ${untracked ? 'before tracking began' : record?.completed ? 'goal completed' : future ? 'future date' : record ? 'goal not completed' : 'no record'}">${dayNumber}</button>`); }
  el('calendar-grid').innerHTML = cells.join(''); const startMonth = parseDate(TRACKING_START_DATE); el('previous-month').disabled = historyMonth.getFullYear() === startMonth.getFullYear() && historyMonth.getMonth() === startMonth.getMonth();
  const selected = parseDate(selectedHistoryDate); const record = recordFor(selectedHistoryDate); const isFuture = !isBeforeToday(selected) && selectedHistoryDate !== state.activeDate; const dateText = new Intl.DateTimeFormat(undefined, { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }).format(selected); let content = `<p class="detail-date">${dateText}</p>`;
  if (!isTrackedKey(selectedHistoryDate)) content += '<p class="detail-count">Not tracked</p><p class="detail-status">History begins July 26, 2026.</p>';
  else if (isFuture) content += '<p class="detail-count">No data yet</p><p class="detail-status">This date is still ahead.</p>';
  else if (!record) content += '<p class="detail-count">No record</p><p class="detail-status">No activity was recorded for this date.</p>';
  else if (record.count === null) content += `<p class="detail-count">${record.completed ? 'Goal met' : 'Not met'}</p><p class="detail-status">The exact count was recorded before history totals were added.</p>`;
  else content += `<p class="detail-count">${record.count} push-up${record.count === 1 ? '' : 's'}</p><p class="detail-status ${record.completed ? 'complete-text' : ''}">${record.completed ? `Goal completed — ${record.goal} goal` : `Goal not completed — ${record.goal} goal`}</p>`;
  if (isTrackedKey(selectedHistoryDate) && !isFuture) content += '<form class="history-add" id="history-add-form"><input id="history-add-amount" inputmode="numeric" type="number" min="1" max="10000" placeholder="Add push-ups" aria-label="Push-ups to add for selected date" /><button type="submit">Add</button></form>';
  el('history-detail').innerHTML = content;
}
function renderReset() { const messages = ['Permanently erase every saved push-up, goal, and history entry from this device.', 'Do you want to hard reset everything?', 'Are you absolutely sure? This cannot be undone.']; const labels = ['Hard reset', 'Yes, reset everything', 'I am sure — erase all data']; el('reset-copy').textContent = messages[resetStep]; el('reset-button').textContent = labels[resetStep]; }
function render() { reconcileDate(); const complete = state.count >= state.goal; const percent = Math.min(100, Math.round((state.count / state.goal) * 100)); el('today-label').textContent = new Intl.DateTimeFormat(undefined, { weekday: 'long', month: 'long', day: 'numeric' }).format(new Date()).toUpperCase(); el('current-count').textContent = state.count; el('goal-count').textContent = state.goal; el('completed-stat').textContent = state.count; el('remaining-stat').textContent = Math.max(0, state.goal - state.count); el('percent').textContent = `${percent}%`; el('goal-input').value = state.goal; const fill = el('progress-fill'); fill.style.width = `${percent}%`; fill.classList.toggle('complete', complete); const bar = document.querySelector('[role="progressbar"]'); bar.setAttribute('aria-valuemax', state.goal); bar.setAttribute('aria-valuenow', state.count); el('completion-message').hidden = !complete; el('streak-count').textContent = calculateStreak(); renderWeek(); renderHistory(); renderReset(); }
function validatePositive(value, maximum = 100000) { const number = Number(value); return Number.isInteger(number) && number > 0 && number <= maximum ? number : null; }

document.querySelectorAll('[data-add]').forEach((button) => button.addEventListener('click', () => changeCount(Number(button.dataset.add)))); document.querySelectorAll('[data-adjust]').forEach((button) => button.addEventListener('click', () => changeCount(Number(button.dataset.adjust))));
el('custom-form').addEventListener('submit', (event) => { event.preventDefault(); const amount = validatePositive(el('custom-amount').value, 10000); if (!amount) { el('custom-error').textContent = 'Enter a whole number between 1 and 10,000.'; return; } el('custom-error').textContent = ''; el('custom-amount').value = ''; changeCount(amount); });
el('goal-input').addEventListener('change', (event) => { const goal = validatePositive(event.target.value); if (!goal) { event.target.value = state.goal; return; } state.goal = goal; saveState(); render(); });
el('previous-month').addEventListener('click', () => { const start = parseDate(TRACKING_START_DATE); if (historyMonth > new Date(start.getFullYear(), start.getMonth(), 1)) { historyMonth = new Date(historyMonth.getFullYear(), historyMonth.getMonth() - 1, 1); renderHistory(); } }); el('next-month').addEventListener('click', () => { historyMonth = new Date(historyMonth.getFullYear(), historyMonth.getMonth() + 1, 1); renderHistory(); });
el('calendar-grid').addEventListener('click', (event) => { const button = event.target.closest('[data-history-date]'); if (!button) return; selectedHistoryDate = button.dataset.historyDate; renderHistory(); });
el('history-detail').addEventListener('submit', (event) => { if (event.target.id !== 'history-add-form') return; event.preventDefault(); const amount = validatePositive(el('history-add-amount').value, 10000); if (!amount) return; if (selectedHistoryDate === state.activeDate) { changeCount(amount); return; } const existing = recordFor(selectedHistoryDate); const goal = existing?.goal || state.goal; const count = (typeof existing?.count === 'number' ? existing.count : 0) + amount; state.history[selectedHistoryDate] = archiveRecord(count, goal); saveState(); render(); });
el('reset-button').addEventListener('click', () => { if (resetStep < 2) { resetStep++; renderReset(); return; } localStorage.removeItem(STORAGE_KEY); state = defaultState(); selectedHistoryDate = dateKey(new Date()); historyMonth = new Date(new Date().getFullYear(), new Date().getMonth(), 1); resetStep = 0; render(); });
document.querySelectorAll('.tab').forEach((tab) => tab.addEventListener('click', () => { const target = tab.dataset.view; document.querySelectorAll('.view').forEach((view) => { const active = view.id === target; view.hidden = !active; view.classList.toggle('active', active); }); document.querySelectorAll('.tab').forEach((item) => { const active = item === tab; item.classList.toggle('active', active); item.toggleAttribute('aria-current', active); }); }));
document.addEventListener('visibilitychange', () => { if (!document.hidden) render(); }); window.addEventListener('focus', render); function scheduleMidnightRefresh() { const now = new Date(); const midnight = new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1); setTimeout(() => { render(); scheduleMidnightRefresh(); }, midnight - now + 250); } if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('service-worker.js')); render(); scheduleMidnightRefresh();
